### PR TITLE
Darktheme Implemented

### PR DESCRIPTION
**Pull request by techimanshu8**

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
1. In Dark Mode all the Links (<a></a>) which are blue colored are not properly visible, E.g. Issue Titles etc. 
2. Also In User Profile Card, various Credential values are not properly visible.

**Comment by techimanshu8** [comment]
@ankitsangwan1999  
Indentions corrected and made links visible

**Comment by ankitsangwan1999** [comment]
In all the PR's Cards(shown in mentors profile), add the icon given below in the left side of the Card header. So that it is easy to diff from Issue Request Cards.

https://fontawesome.com/v5.15/icons/bullseye?style=light

**Comment by pirateksh** [comment]
@techimanshu8  Did you push code for both the Issues (Collapsible Navbar and Dark Theme) in the same branch?

**Comment by pirateksh** [comment]
> > > > @techimanshu8 Did you push code for both the Issues (Collapsible Navbar and Dark Theme) in the same branch?
> > > 
> > > 
> > > sir i was working on dark theme in main branch , then i create new branch named NavbarFix and implemented collapsible navbar .
> > 
> > 
> > What did you do in this commit? -
> > ```
> > commit 276028805478746833e797499ab6b184de7d8a9c
> > Author: techimanshu8 <himanshusaini6969@gmail.com>
> > Date:   Sun Oct 10 09:50:00 2021 +0530
> > 
> >     Delete previus changes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And in which branch was this?
> > Because when I merged Collapsible Navbar PR, the PR of Dark Mode also got merge automatically somehow. But I cannot see the changes you made for Darkmode in the **main** branch now.
> 
> Sir actually , when i create new branch NavFix , it was copy of main branch which contains code of dark theme also so ,i deleted that code , to implement collapsible navbar .

Ok so do one thing, Create a New PR for dark mode with the changes, because currently in the merged branch those changes are not present, and this PR has been merged as well.

So create a new PR and send its link to me on ms teams.

**Pull request merged**
