### PR TITLE
Added Contact Us Form Issue #18

### LINKED ISSUE #18: Add Contact Us Form
Add a **Contact Us** Form where user can Enter their query and when they hit submit, an email should be sent to contrihub.avishkar@gmail.com

Use Django Crispy Form for styling the form.

### PR DESCRIPTION
**Pull request by DuP-491**
fixes #18 
Added Contact Form which can be used by authenticated users via navbar

### CODE REVIEW

**Comment by DuP-491** [comment]
added proper indentation in all concerned files

**Comment by ankitsangwan1999** [comment]
Checking Now

**Comment by DuP-491** [comment]
updated requirements.txt

**Comment by ankitsangwan1999** [comment]
Checked. Merging Now

**Pull request merged**
