### PR TITLE
upvote/downvote #27

### LINKED ISSUE #27: Up/Down Vote Issue Feature
* Implement an Up-Vote Down-Vote Issue Feature using AJAX on the Homepage.
* When the button is clicked, a toast should display the message "Upvoted" or "Downvoted".
* 1 person 1 vote (either Upvote or Downvote) per issue.
* Show counts of upvotes and downvotes on the Issue card next to the buttons.

### PR DESCRIPTION
**Pull request by DuP-491**
fixes #27 

Implemented upvote/downvote feature using ajax and bootstrap toast

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Important:-
In projects/admin.py file, Update the IssueAdmin class as follows. This ensures upvotes/downvotes count shown in admin panel for each issue.

class IssueAdmin(admin.ModelAdmin):
    list_display = ('id', 'title', 'number', 'project', 'mentor', 'level', 'points', 'state', 'get_upvotes_cnt', 'get_downvotes_cnt')

    @display(ordering='issue__upvotes', description='Count of Upvotes')
    def get_upvotes_cnt(self, obj):
        return obj.upvotes.all().count()


    @display(ordering='issue__downvotes', description='Count of Downvotes')
    def get_downvotes_cnt(self, obj):
        return obj.downvotes.all().count()

**Comment by ankitsangwan1999** [comment]
PROBLEM:

When I am Upvoting and Downvoting an issue the count is not updated instantly for that issue. Instead, this info is updated for the first issue always.

NOTE:- You have used a separate HTML file for defining Upvoted/Downvoted successfully message. Instead what you are required to do is use Django-messages to set the toast message from the backend itself, And instead of using this separate HTML file for upvote/downvote toast only, write a common login for showing whatever message is there in django-messages as toast. This will be done in a js file which you can include in the scripts.html file.

Q: Why do you need to do this?
Ans: Because if we want to show other toast messages in the front-end or want to change the toast message for upvotes/downvotes in views.py only. Also, We will not be required to create separate HTML files for each toast message we will add in the future.

**Comment by ankitsangwan1999** [comment]
If the deadline of the Issue is crossed. Don't worry we will still consider your commit till MAX(deadline-Time, 11Oct-10-AM)

**Comment by DuP-491** [comment]
@ankitsangwan1999 added linebreak after button
update admin panel code as intended
fixed announcement in index html
about issue updation I added unique id for issue displayed and accordingly updated them individually

apologies for making so many errors

**Comment by ankitsangwan1999** [comment]
Hey @DuP-491, Closing this PR here, I have updated some of your partial progress in the main branch already. You will get 20 points as per the updated level of this issue. You may finish the un-implemented part by requesting the new issue that we will create.

**Pull request closed without merging**
