### PR TITLE
Added Bonus Badge

### LINKED ISSUE #43: Show badge on card of issues having bonus.
Mentors have bonus points (a +5 label with bonus description) for some issues that show it as a badge on the top-left side of the issue cards

### PR DESCRIPTION
**Pull request by rdx-rockstar**
fixes #43

### CODE REVIEW

**Comment by ankitsangwan1999** [comment]
Changes:-
1. You are required to make changes in populate_issues view also, as if an issue have bonus label as one of its labels then it should be updated in the database.
2. Also the bonus description should be mentioned in the upper-left corner of the card. Check my comment on the issue for more detail.

**Comment by rdx-rockstar** [comment]
changed the bonus badge position.

**Comment by ankitsangwan1999** [comment]
I think you are always showing +5 as bonus (Correct me if I am wrong). if it is so, then you have to change it because the label (with bonus as description) can be any-other string also, like +7, +5 for abc etc. hence this string should be shown in the badge.

**Comment by ankitsangwan1999** [comment]
> @ankitsangwan1999 yes, for now, it will always show a +5 badge. But the problem is from where should I take the bonus value.
> 
> 1. * one way can be to get value by subtracting points from the default points.
> 2. * or you may have to create (In git hub) new labels for each bonus point issues with label description "bonus" and label name be +5,+7, etc (which are not there at present, or maybe I haven't found one till now).
> 3. * or you may suggest another way.
> 
> For now, there is no bonus description. should the bonus description be like "+5 for creativity" or just "+5"; if like "+5 for creativity" where would it be written in the issue like in the issue's label description or name?

Clarifications:
1. Second Point is correct Implementation. If some issue is having bonus, then we as mentors will mention that as a single label with label-name as the string itself e.g. +5, +7 for creativity etc. and label-description as "bonus". So, if You find any issue with a label-description as "bonus", show that label-name in the badge. 
2. Calculation of bonus by subtraction of actual points - default points is not needed as this value is technically not "bonus". In short, a bonus somewhat conditional. So, if the Some Issue is having non-default points then, you can highlight that thing in the button showing the points itself.

**Comment by rdx-rockstar** [comment]
@ankitsangwan1999 
is it right now?
Screenshot (13)

**Pull request merged**
